server:
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization:
      indent_output: true
logging:
  level:
   com:
    debug
